name: artisans_app
description: A beautiful Flutter app for displaying artisans services and login functionality.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.28.0
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.0
  flutter_rating_bar: ^4.0.0
  modal_progress_hud_nsn: ^0.5.1
  image_picker: ^1.0.8
  path: ^1.9.0
  firebase_database: ^10.5.0
  awesome_dialog: ^3.2.0
  get: ^4.6.6
  fluttertoast: ^8.0.8
  convex_bottom_bar: ^3.2.0
  firebase_storage: ^11.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  # إضافة الصور هنا
  assets:
    - images/
  
    
